---
name: "CI"

on:
  push:
    branches:
      - main

env:
  IMAGE: europe-docker.pkg.dev/nube-hub/docker/aplineal

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
